[book]
authors = ["Christian Kaestner"]
language = "en"
multilingual = false
src = "."
title="Machine Learning in Production: From Models to Products"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
mathjax-support = false
git-repository-url = "https://github.com/mlip-cmu/book"
git-repository-icon = "fa-github"

[build]
extra-watch-dirs = ["README.md"] 

[output.html.redirect]
"/01/index.html" = "../01-introduction.html"
"/02/index.html" = "../02-from-models-to-systems.html"
"/03/index.html" = "../03-machine-learning-for-software-engineers-in-a-nutshell.html"
"/04/index.html" = "../04-when-to-use-machine-learning.html"
"/05/index.html" = "../05-setting-and-measuring-goals.html"
"/06/index.html" = "../06-gathering-requirements.html"
"/07/index.html" = "../07-planning-for-mistakes.html"
"/08/index.html" = "../08-thinking-like-a-software-architect.html"
"/09/index.html" = "../09-quality-attributes-of-ml-components.html"
"/10/index.html" = "../10-deploying-a-model.html"
"/11/index.html" = "../11-automating-the-pipeline.html"
"/12/index.html" = "../12-scaling-the-system.html"
"/13/index.html" = "../13-planning-for-operations.html"
"/14/index.html" = "../14-quality-assurance-basics.html"
"/15/index.html" = "../15-model-quality.html"
"/16/index.html" = "../16-data-quality.html"
"/17/index.html" = "../17-pipeline-quality.html"
"/18/index.html" = "../18-system-quality.html"
"/19/index.html" = "../19-testing-and-experimenting-in-production.html"
"/20/index.html" = "../20-data-science-and-software-engineering-process-models.html"
"/21/index.html" = "../21-interdisciplinary-teams.html"
"/22/index.html" = "../22-technical-debt.html"
"/23/index.html" = "../23-responsible-engineering.html"
"/24/index.html" = "../24-versioning-provenance-and-reproducibility.html"
"/25/index.html" = "../25-explainability.html"
"/26/index.html" = "../26-fairness.html"
"/27/index.html" = "../27-safety.html"
"/28/index.html" = "../28-security-and-privacy.html"
"/29/index.html" = "../29-transparency-and-accountability.html"
